# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glitch Hermeneutics
email: alex.sosn88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Oleksandr (Alex) Sosnovshchenko and this is my blog. It contains some occasional notes on random topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alexsosn.github.io/" # the base hostname & protocol for your site
twitter_username: StecOverflow
github_username: alexsosn

# Build settings
markdown: kramdown
